# Generated by Django 5.2.7 on 2026-03-18 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0002_permiso_rol_profile_fecha_nacimiento_profile_rol_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='destacado',
            field=models.BooleanField(default=False, help_text='Marcar para mostrar en la página principal como destacado'),
        ),
    ]
