# Generated by Django 5.2.7 on 2026-03-13 01:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0002_categoria_slug_producto'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Cart',
            new_name='Carrito',
        ),
        migrations.RemoveField(
            model_name='cartitem',
            name='size',
        ),
        migrations.RenameField(
            model_name='cartitem',
            old_name='cart',
            new_name='carrito',
        ),
        migrations.RemoveField(
            model_name='cartitem',
            name='flavors',
        ),
        migrations.RemoveField(
            model_name='cartitem',
            name='quantity',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='disponible',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='precio',
        ),
        migrations.RemoveField(
            model_name='sabor',
            name='price',
        ),
        migrations.AddField(
            model_name='cartitem',
            name='cantidad',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='cartitem',
            name='precio_unitario',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cartitem',
            name='producto',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='pedidos.producto'),
        ),
        migrations.AddField(
            model_name='cartitem',
            name='sabores',
            field=models.ManyToManyField(blank=True, to='pedidos.sabor'),
        ),
        migrations.AddField(
            model_name='producto',
            name='precio_base',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='producto',
            name='stock',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='sabor',
            name='activo',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='sabor',
            name='precio_extra',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
        migrations.AddField(
            model_name='sabor',
            name='slug',
            field=models.SlugField(default=0, unique=True),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Tamano',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('slug', models.SlugField(unique=True)),
                ('precio_extra', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('activo', models.BooleanField(default=True)),
                ('categoria', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pedidos.categoria')),
            ],
        ),
        migrations.CreateModel(
            name='ProductoTamano',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('precio', models.DecimalField(decimal_places=2, max_digits=6)),
                ('producto', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='pedidos.producto')),
                ('tamano', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='pedidos.tamano')),
            ],
            options={
                'unique_together': {('producto', 'tamano')},
            },
        ),
        migrations.AddField(
            model_name='cartitem',
            name='tamano',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='pedidos.tamano'),
        ),
        migrations.DeleteModel(
            name='Size',
        ),
    ]
