# Generated by Django 5.2.7 on 2026-03-20 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0003_producto_destacado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoria',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='images/Categorias/'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='images/Productos/'),
        ),
        migrations.AlterField(
            model_name='sabor',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='images/Sabores/'),
        ),
    ]
