# Generated by Django 5.2.7 on 2026-03-21 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0004_alter_categoria_imagen_alter_producto_imagen_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tamano',
            name='precio_extra',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=10),
        ),
    ]
