# Generated by Django 5.2.7 on 2026-03-26 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0005_alter_tamano_precio_extra'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='metodo_pago',
            field=models.CharField(blank=True, choices=[('efectivo', 'Efectivo'), ('transferencia', 'Transferencia bancaria')], default='efectivo', max_length=20),
        ),
        migrations.AddField(
            model_name='pedido',
            name='pago_confirmado',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='precio_unitario',
            field=models.DecimalField(decimal_places=0, max_digits=10),
        ),
    ]
