# Generated by Django 5.2.7 on 2026-03-30 15:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0006_pedido_metodo_pago_pedido_pago_confirmado_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='detallecompra',
            name='fecha_ingreso',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2026, 3, 30, 15, 40, 6, 538526, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='insumo',
            name='ultima_operacion',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='producto',
            name='precio_base',
            field=models.DecimalField(blank=True, decimal_places=0, default=0, max_digits=10),
        ),
    ]
