# Generated by Django 5.2.7 on 2026-04-06 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0007_detallecompra_fecha_ingreso_insumo_ultima_operacion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='insumo',
            name='precio_unitario_promedio',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=10),
        ),
    ]
