# Generated by Django 5.2.7 on 2026-04-20 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0010_alter_addon_price_alter_caja_monto_final_contado_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='unidadmedida',
            name='factor_conversion',
            field=models.DecimalField(decimal_places=2, default=1, help_text='Factor para convertir a unidad base. Ej: kg=1000, g=1, L=1000', max_digits=10),
        ),
    ]
