# Generated by Django 5.2.7 on 2026-04-27 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0012_produccionlog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receta',
            name='cantidad_requerida',
            field=models.DecimalField(decimal_places=4, max_digits=10),
        ),
    ]
