# Generated by Django 5.2.7 on 2026-04-27 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0013_alter_receta_cantidad_requerida'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produccionlog',
            name='cantidad_producida',
        ),
        migrations.AddField(
            model_name='produccionlog',
            name='cantidad_planificada',
            field=models.PositiveIntegerField(default=1, help_text='Cantidad que se planificó producir'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='produccionlog',
            name='cantidad_real',
            field=models.PositiveIntegerField(blank=True, help_text='Cantidad real que salió de la producción', null=True),
        ),
        migrations.AddField(
            model_name='produccionlog',
            name='estado',
            field=models.CharField(choices=[('en_proceso', 'En proceso'), ('completada', 'Completada')], default='en_proceso', max_length=20),
        ),
        migrations.AddField(
            model_name='produccionlog',
            name='fecha_completada',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
