# Generated by Django 5.2.7 on 2026-04-30 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0014_remove_produccionlog_cantidad_producida_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produccionlog',
            name='cantidad_planificada',
            field=models.DecimalField(decimal_places=3, help_text='Cantidad que se planificó producir', max_digits=10),
        ),
        migrations.AlterField(
            model_name='produccionlog',
            name='cantidad_real',
            field=models.DecimalField(blank=True, decimal_places=3, help_text='Cantidad real que salió de la producción', max_digits=10, null=True),
        ),
    ]
