# Generated by Django 5.2.7 on 2026-04-30 00:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0015_alter_produccionlog_cantidad_planificada_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='egreso',
            name='nro_comprobante',
            field=models.CharField(blank=True, default='', help_text='Número de factura o comprobante', max_length=50),
        ),
        migrations.AddField(
            model_name='egreso',
            name='proveedor',
            field=models.ForeignKey(blank=True, help_text='Proveedor asociado al egreso (opcional)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='egresos', to='pedidos.proveedor'),
        ),
    ]
