# Generated by Django 5.2.7 on 2026-05-10 22:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0016_egreso_nro_comprobante_egreso_proveedor'),
    ]

    operations = [
        migrations.RenameField(
            model_name='addon',
            old_name='name',
            new_name='nombre',
        ),
        migrations.RemoveField(
            model_name='addon',
            name='price',
        ),
        migrations.AddField(
            model_name='addon',
            name='activo',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='addon',
            name='cantidad_descontar',
            field=models.DecimalField(decimal_places=4, default=0, help_text='Cantidad a descontar del insumo (en unidad base, ej: gramos)', max_digits=10),
        ),
        migrations.AddField(
            model_name='addon',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='images/Addons/'),
        ),
        migrations.AddField(
            model_name='addon',
            name='insumo',
            field=models.ForeignKey(blank=True, help_text='Insumo que se descuenta al elegir este agregado', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='addons', to='pedidos.insumo'),
        ),
        migrations.AddField(
            model_name='addon',
            name='precio_extra',
            field=models.DecimalField(decimal_places=0, default=0, help_text='Costo extra para el cliente (puede ser 0)', max_digits=10),
        ),
        migrations.AddField(
            model_name='tamano',
            name='max_sabores',
            field=models.PositiveIntegerField(default=1, help_text='Cantidad máxima de sabores que puede elegir el cliente'),
        ),
    ]
