# Generated by Django 5.2.7 on 2026-05-10 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0017_rename_name_addon_nombre_remove_addon_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tamano',
            name='solo_produccion',
            field=models.BooleanField(default=False, help_text='Si está marcado, este tamaño no se muestra a clientes'),
        ),
    ]
