# Generated by Django 5.2.7 on 2026-05-10 23:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0018_tamano_solo_produccion'),
    ]

    operations = [
        migrations.AddField(
            model_name='sabor',
            name='gramos_por_porcion',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Gramos que se descuentan por porción al pedir este sabor. Se puede sobreescribir por categoría de tamaño.', max_digits=8),
        ),
        migrations.AddField(
            model_name='sabor',
            name='insumo_stock',
            field=models.ForeignKey(blank=True, help_text='Insumo de producción que representa este sabor (para verificar disponibilidad)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sabores_asociados', to='pedidos.insumo'),
        ),
    ]
