# Generated by Django 5.2.7 on 2026-05-18 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0019_sabor_gramos_por_porcion_sabor_insumo_stock'),
    ]

    operations = [
        migrations.AddField(
            model_name='addon',
            name='categorias',
            field=models.ManyToManyField(blank=True, help_text='Categorías donde se muestra este agregado. Si no seleccionás ninguna, aparece en todas.', related_name='addons', to='pedidos.categoria'),
        ),
        migrations.AlterField(
            model_name='insumo',
            name='ultima_operacion',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
    ]
