# Generated by Django 5.2.7 on 2026-05-24 23:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0020_addon_categorias_alter_insumo_ultima_operacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='sabor',
            name='categorias_extra',
            field=models.ManyToManyField(blank=True, help_text='sabores', related_name='sabores_extra', to='pedidos.categoria'),
        ),
        migrations.CreateModel(
            name='Subcategoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('activo', models.BooleanField(default=True)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subcategorias', to='pedidos.categoria')),
            ],
            options={
                'ordering': ['nombre'],
            },
        ),
    ]
