# Generated by Django 5.2.7 on 2026-05-25 13:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0021_sabor_categorias_extra_subcategoria'),
    ]

    operations = [
        migrations.AddField(
            model_name='sabor',
            name='subcategoria',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sabores', to='pedidos.subcategoria'),
        ),
    ]
